Fix telemetry test (#1943)
<!--
Ensure the title clearly reflects what was changed.
Provide a clear and concise description of the changes made. The PR
should only contain the changes related to the issue, and no other
unrelated changes.
-->

Fixes OPS-3651

```
  ● telemetry › trackEvent › should save metric to Logzio if no telemetry URL

    TypeError: Date.now is not a function

      at wait (../../../node_modules/thread-stream/lib/wait.js:6:20)
      at ThreadStream.flush (../../../node_modules/thread-stream/index.js:298:5)
      at Worker.onWorkerMessage (../../../node_modules/thread-stream/index.js:169:14)
```